INSERT INTO menu(name, catalog, price)
VALUES 
('Edamame', 'Appetizer', 5.00),
('Agedashi Tofu', 'Appetizer', 5.00),
('Yakitori', 'Appetizer', 5.00),
('Vegetable Tempura', 'Appetizer', 5.00),
('Chicken Tempura', 'Appetizer', 6.00),
('Yaki Ebi', 'Appetizer', 6.00),
('Harumaki Shrimp Spring Roll', 'Appetizer', 6.00),
('Gyoza', 'Appetizer', 6.00),
('Tokyo Shumai', 'Appetizer', 6.00),
('Shrimp Tempura', 'Appetizer', 7.00),
('Battered Butterfly Shrimp', 'Appetizer', 8.00),
('Calamari Katsu', 'Appetizer', 8.00),
('Beef Negimaki', 'Appetizer', 8.00),
('Fried Oyster', 'Appetizer', 8.00),
('Soft Shell Crab', 'Appetizer', 9.00),
('Ichiban Combo Platter', 'Appetizer', 11.00),
('Seaweed Salad', 'Appetizer', 6.00),
('Squid Salad', 'Appetizer', 7.00),
('Sunomono', 'Appetizer', 7.00),
('Baked Mussels', 'Appetizer', 7.00),
('Crab Salad', 'Appetizer', 7.00),
('Naruto', 'Appetizer', 8.00),
('Sushi Appetizers', 'Appetizer', 9.00),
('Sashimi Appetizers', 'Appetizer', 10.00),
('Tuna Tataki', 'Appetizer', 12.00),
('Vegetable', 'Hibachi Dinner', 14.00),
('Chicken', 'Hibachi Dinner', 17.00),
('Salmon', 'Hibachi Dinner', 19.00),
('Shrimp', 'Hibachi Dinner', 20.00),
('Steak', 'Hibachi Dinner', 20.00),
('Tuna', 'Hibachi Dinner', 20.00),
('Sea Scallops', 'Hibachi Dinner', 21.00),
('Filet Mignon', 'Hibachi Dinner', 23.00),
('Twin Lobster Tail', 'Hibachi Dinner', 29.00),
('Chicken & Shrimp', 'Hibachi Combo', 22.00),
('Chicken & Steak', 'Hibachi Combo', 22.00),
('Chicken & Filet Mignon', 'Hibachi Combo', 25.00),
('Chicken & Lobster', 'Hibachi Combo', 27.00),
('Shrimp & Steak', 'Hibachi Combo', 24.00),
('Shrimp & Scallops', 'Hibachi Combo', 24.00),
('Shrimp & Filet Mignon', 'Hibachi Combo', 26.00),
('Shrimp & Lobster', 'Hibachi Combo', 27.00),
('Steak & Salmon', 'Hibachi Combo', 24.00),
('Steak & Tuna', 'Hibachi Combo', 24.00),
('Filet Mignon & Lobster', 'Hibachi Combo', 29.00),
('Seafood Combo', 'Hibachi Combo', 30.00),
('Ichiban V.I.P. Special Dinner', 'Hibachi Combo', 58.00),
('Share Plate', 'Hibachi Combo', 5.00),
('Steamed Rice', 'Side Orders', 2.00),
('Miso Soup', 'Side Orders', 2.00),
('Clear Soup', 'Side Orders', 3.00),
('House Salad', 'Side Orders', 3.00),
('Fried Rice', 'Side Orders', 4.00),
('Vegetable', 'Side Orders', 5.00),
('Chicken', 'Side Orders', 6.00),
('Tuna', 'Side Orders', 7.00),
('Scallops', 'Side Orders', 7.00),
('King Salmon', 'Side Orders', 7.00),
('Steak', 'Side Orders', 8.00),
('Shrimp', 'Side Orders', 8.00),
('Filet Mignon', 'Side Orders', 10.00),
('Lobster Tail', 'Side Orders', 15.00),
('Vegetable', 'Teriyaki', 14.00),
('Chicken', 'Teriyaki', 17.00),
('Salmon', 'Teriyaki', 19.00),
('Shrimp', 'Teriyaki', 20.00),
('Steak', 'Teriyaki', 20.00),
('Tuna', 'Teriyaki', 20.00),
('Sea Scallops', 'Teriyaki', 21.00),
('Filet Mignon', 'Teriyaki', 23.00),
('Twin Lobster Tail', 'Teriyaki', 29.00),
('Chicken', 'Katsu', 15.00),
('Pork', 'Katsu', 15.00),
('Fish', 'Katsu', 17.00),
('Vegetable', 'Tempura', 12.00),
('Chicken', 'Tempura', 15.00),
('Shrimp', 'Tempura', 17.00),
('Chiken & Shrimp', 'Tempura', 20.00),
('Tempura Udon', 'Noodle Soup', 14.00),
('Chicken Udon', 'Noodle Soup', 15.00),
('Seafood Udon', 'Noodle Soup', 16.00),
('Yaki Udon with Chicken & Beef', 'Stir-Fried Noodles', 14.00),
('Yaki Sobo with Chicken & Beef', 'Stir-Fried Noodles', 14.00),
('Yaki Udon with Seafood', 'Stir-Fried Noodles', 16.00),
('Yaki Sobo with Seafood', 'Stir-Fried Noodles', 16.00),
('Chirashi', 'SUSHI BAR ENTREES', 16.00),
('Unagi Don', 'SUSHI BAR ENTREES', 18.00),
('Sushi Regular', 'SUSHI BAR ENTREES', 19.00),
('Sashimi Regular', 'SUSHI BAR ENTREES', 22.00),
('Sushi Deluxe', 'SUSHI BAR ENTREES', 23.00),
('Sushi & Sashimi Combo', 'SUSHI BAR ENTREES', 25.00),
('Love Boat for Two', 'SUSHI BAR ENTREES', 53.00),
('Oshinoko Roll', 'REGULAR ROLLS', 3.50),
('Kampyo Roll', 'REGULAR ROLLS', 3.50),
('Asparagus Roll', 'REGULAR ROLLS', 3.50),
('Cucumber Roll', 'REGULAR ROLLS', 3.50),
('Avocado Roll', 'REGULAR ROLLS', 3.50),
('Salmon Roll', 'REGULAR ROLLS', 4.25),
('Shrimp Roll', 'REGULAR ROLLS', 4.75),
('Crab Roll', 'REGULAR ROLLS', 4.75),
('Tuna Roll', 'REGULAR ROLLS', 4.75),
('California Roll', 'REGULAR ROLLS', 4.75),
('Salmon Skin Roll', 'REGULAR ROLLS', 4.75),
('Alaska Roll', 'REGULAR ROLLS', 4.75),
('Vegetable Roll', 'REGULAR ROLLS', 4.75),
('Spicy California Roll', 'REGULAR ROLLS', 4.95),
('Philadelphia Roll', 'REGULAR ROLLS', 5.25),
('Salmon Avocado Roll', 'REGULAR ROLLS', 5.25),
('Yellowtail Roll', 'REGULAR ROLLS', 5.95),
('Spicy Salmon Roll', 'REGULAR ROLLS', 5.95),
('Futo Maki Roll', 'REGULAR ROLLS', 5.95),
('Tuna Avocado Roll', 'REGULAR ROLLS', 5.95),
('Shrimp Asparagus Roll', 'REGULAR ROLLS', 5.95),
('Eel Roll', 'REGULAR ROLLS', 6.95),
('Spicy Tuna Roll', 'REGULAR ROLLS', 6.95),
('Crispy Spicy Tuna Roll', 'REGULAR ROLLS', 6.95),
('J.B Roll', 'SPECIAL ROLLS', 8.00),
('Dynamite Roll', 'SPECIAL ROLLS', 8.00),
('Spider Roll', 'SPECIAL ROLLS', 10.00),
('Volcano Roll', 'SPECIAL ROLLS', 10.00),
('Green Dragon Roll', 'SPECIAL ROLLS', 10.00),
('Crazy Roll', 'SPECIAL ROLLS', 11.00),
('Tiger Eye Roll', 'SPECIAL ROLLS', 11.00),
('Double Spicy Roll', 'SPECIAL ROLLS', 11.00),
('Fire House Roll', 'SPECIAL ROLLS', 11.00),
('Rainbow Roll', 'SPECIAL ROLLS', 11.00),
('Happy Dragon Roll', 'SPECIAL ROLLS', 12.00),
('M I Roll', 'SPECIAL ROLLS', 13.00),
('Ann Arbor Roll', 'SPECIAL ROLLS', 13.00),
('Ichiban Roll', 'SPECIAL ROLLS', 13.00),
('Delicious Roll', 'SPECIAL ROLLS', 13.00),
('Tempura Lobster Roll', 'SPECIAL ROLLS', 14.00),
('Egg', 'NIGIRI', 1.75),
('Tofu Skin', 'NIGIRI', 1.75),
('Crab Stick', 'NIGIRI', 2.00),
('Squid', 'NIGIRI', 2.00),
('Shrimp', 'NIGIRI', 2.25),
('Red Snapper', 'NIGIRI', 2.25),
('Mackerel', 'NIGIRI', 2.25),
('Salmon', 'NIGIRI', 2.25),
('White Tuna', 'NIGIRI', 2.25),
('Masago', 'NIGIRI', 2.50),
('Tuna', 'NIGIRI', 2.75),
('Octopus', 'NIGIRI', 2.75),
('Tobiko', 'NIGIRI', 2.75),
('Yellowtail', 'NIGIRI', 2.75),
('Smoked Salmon', 'NIGIRI', 2.75),
('Smoked Eel', 'NIGIRI', 2.95),
('Salmon Roe', 'NIGIRI', 3.25),
('Scallop', 'NIGIRI', 3.50),
('Raw Sweet Shrimp', 'NIGIRI', 3.95),
('Spicy Crispy Scallop', 'NIGIRI', 3.95),
('Sea Urchin', 'NIGIRI', 4.00),
('Belly Tuna', 'NIGIRI', 6.00),
('Ice Cream', 'DESSERTS', 4.00),
('Cheesecake', 'DESSERTS', 5.00),
('Tempura Ice Cream', 'DESSERTS', 6.00),
('Tempura Cheesecake', 'DESSERTS', 6.00),
('Bahama Mama', 'COCKTAILS', 1.75),
('Mai Tai', 'COCKTAILS', 2.00),
('Zombie', 'COCKTAILS', 2.00),
('Pina Colada', 'COCKTAILS', 2.25),
('Blue Tsunami', 'COCKTAILS', 2.25),
('Margarita', 'COCKTAILS', 2.25),
('Long Island Iced Tea', 'COCKTAILS', 2.25),
('Jamacian Itch', 'COCKTAILS', 2.25),
('Ichiban Volcano', 'COCKTAILS', 2.50),
('Anzu Martini', 'MARTINIS', 8.95),
('Rising Sun', 'MARTINIS', 8.95),
('Lychee Martini', 'MARTINIS', 8.95),
('Tokyo Night', 'MARTINIS', 8.95),
('Apple Martini', 'MARTINIS', 8.95),
('Carmel Aplle Martini', 'MARTINIS', 8.95),
('Ichiban Lemon Drop', 'MARTINIS', 8.95),
('Shogun Sake Martini', 'MARTINIS', 8.95),
('Plum Yumm', 'MARTINIS', 8.95),
('Blue Raspberry', 'MARTINIS', 8.95);
