CREATE TABLE employee_info(
	first_name VARCHAR(20) NOT NULL,
	last_name VARCHAR(20) NOT NULL,
	DOB VARCHAR(20) NOT NULL,
	SSN INTEGER NOT NULL,
	PASSWORD INTEGER NOT NULL,
	PRIMARY KEY(PASSWORD)
);

CREATE TABLE menu(
	name VARCHAR(20) NOT NULL,
	catalog VARCHAR(20) NOT NULL,
	price REAL NOT NULL,
	PRIMARY KEY(name)
);

